In [4]:
#library imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as ptl 

In [6]:
#dataset imports
data = pd.read_csv('C:/Users/admin/Desktop/capitalbikeshare-tripdata.csv')

In [15]:
data.head()

Duration       Start date         End date  Start station number  \
0      1012  9/20/2010 11:27  9/20/2010 11:43                 31208   
1        61  9/20/2010 11:41  9/20/2010 11:42                 31209   
2      2690  9/20/2010 12:05  9/20/2010 12:50                 31600   
3      1406  9/20/2010 12:06  9/20/2010 12:29                 31600   
4      1413  9/20/2010 12:10  9/20/2010 12:34                 31100   

                   Start station  End station number  \
0       M St & New Jersey Ave SE               31108   
1                 1st & N St  SE               31209   
2                  5th & K St NW               31100   
3                  5th & K St NW               31602   
4  19th St & Pennsylvania Ave NW               31201   

                     End station Bike number Member type  
0                  4th & M St SW      W00742      Member  
1                 1st & N St  SE      W00032      Member  
2  19th St & Pennsylvania Ave NW      W00993      Member  
3        Park Rd & Holmead Pl NW      W00344      Member  
4                 15th & P St NW      W00883      Member

In [11]:
print(data.describe())

            Duration  Start station number  End station number
count  115597.000000         115597.000000       115597.000000
mean     1254.649956          31266.213431        31268.042250
std      2914.317998            187.645048          186.194316
min        60.000000          31000.000000        31000.000000
25%       403.000000          31110.000000        31111.000000
50%       665.000000          31213.000000        31214.000000
75%      1120.000000          31301.000000        31238.000000
max     85644.000000          31805.000000        31805.000000


In [ ]:
#links
#https://www.shanelynn.ie/select-pandas-dataframe-rows-and-columns-using-iloc-loc-and-ix/
#iloc-> selects data by row number

In [33]:
#features and class label seperation
 
x=data.iloc[:,[0,3,5]].values
y=data.iloc[:,-1].values
print(x[:5])
print(y[:5])

[[ 1012 31208 31108]
 [   61 31209 31209]
 [ 2690 31600 31100]
 [ 1406 31600 31602]
 [ 1413 31100 31201]]
['Member' 'Member' 'Member' 'Member' 'Member']


In [45]:
#y needs encoding as it has categorical data
#
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y1 = le.fit_transform(y)
print("sample y:",y1[:5])
print("0 :",le.classes_[0])
print("1 :",le.classes_[1])

sample y: [1 1 1 1 1]
0 : Casual
1 : Member


In [53]:
#Splitting of Data into Training & Testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y1,test_size=0.25,random_state=0)  
print(y_test[:5])
print(x_test[:5])



[1 1 1 1 1]
[[  234 31111 31229]
 [ 1264 31108 31221]
 [  441 31200 31104]
 [  721 31104 31204]
 [  876 31200 31236]]


In [72]:
# Machine: Classifier | Classifier: Decision Tree
from sklearn.tree import DecisionTreeClassifier
#by default criterion=gini


In [80]:
# Predicting the Test set results of entropy -> is the mesasure of randomness
# low entropy means high information gain and vice versa
cl_en = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=4, random_state=0)
cl_en.fit(x_train, y_train)
cl_en

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=4, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [76]:
y_pred = cl_en.predict(x_test)
print("Predicting results of entropy: ")
print(y_pred)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

print("Confusion Matrix: \n",confusion_matrix(y_test, y_pred)) 
print ("Accuracy : \n",accuracy_score(y_test,y_pred)*100) 
print("Report : \n",classification_report(y_test, y_pred)) 


Predicting results of entropy: 
[1 1 1 ... 1 1 1]
Confusion Matrix: 
 [[ 3368  2721]
 [ 2641 20170]]
Accuracy : 
 81.44636678200692
Report : 
               precision    recall  f1-score   support

           0       0.56      0.55      0.56      6089
           1       0.88      0.88      0.88     22811

    accuracy                           0.81     28900
   macro avg       0.72      0.72      0.72     28900
weighted avg       0.81      0.81      0.81     28900



In [75]:
cl_gini = DecisionTreeClassifier(criterion='gini', min_samples_leaf=4, random_state=0)
cl_gini.fit(x_train, y_train)
y_pred = cl_gini.predict(x_test)
print("Predicting results of entropy: ")
print(y_pred)
print("Confusion Matrix: \n",confusion_matrix(y_test, y_pred)) 
print ("Accuracy : \n",accuracy_score(y_test,y_pred)*100) 
print("Report : \n",classification_report(y_test, y_pred)) 


Predicting results of entropy: 
[1 1 1 ... 1 1 1]
Confusion Matrix: 
 [[ 3398  2691]
 [ 2573 20238]]
Accuracy : 
 81.78546712802768
Report : 
               precision    recall  f1-score   support

           0       0.57      0.56      0.56      6089
           1       0.88      0.89      0.88     22811

    accuracy                           0.82     28900
   macro avg       0.73      0.72      0.72     28900
weighted avg       0.82      0.82      0.82     28900

